AutoOA/AutoOA.UI/Controllers/VehiclesController.cs
using AutoOA.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using AutoOA.Repository.Repositories;
using AutoOA.Repository.Dto.VehicleDto;
using AutoOA.Core;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace AutoOA.UI.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ILogger<VehiclesController> _logger;

        private readonly VehicleRepository _vehicleRepository;
        private readonly RegionRepository _regionRepository;
        private readonly VehicleModelRepository _vehicleModelRepository;
        private readonly VehicleBrandRepository _vehicleBrandRepository;
        private readonly FuelTypeRepository _fuelTypeRepository;
        private readonly GearBoxRepository _gearBoxRepository;
        private readonly DriveTypeRepository _driveTypeRepository;
        private readonly BodyTypeRepository _bodyTypeRepository;
        private readonly SalesDataRepository _salesDataRepository;
        private readonly UsersRepository _usersRepository;

        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public VehiclesController(ILogger<VehiclesController> logger, VehicleRepository vehicleRepository,
            RegionRepository regionRepository, VehicleModelRepository vehicleModelRepository,
            VehicleBrandRepository vehicleBrandRepository, FuelTypeRepository fuelTypeRepository,
            GearBoxRepository gearBoxRepository, SignInManager<User> signInManager,
            DriveTypeRepository driveTypeRepository, BodyTypeRepository bodyTypeRepository,
            SalesDataRepository salesDataRepository, UsersRepository usersRepository,
            UserManager<User> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            _vehicleRepository = vehicleRepository;
            _regionRepository = regionRepository;
            _vehicleModelRepository = vehicleModelRepository;
            _vehicleBrandRepository = vehicleBrandRepository;
            _fuelTypeRepository = fuelTypeRepository;
            _gearBoxRepository = gearBoxRepository;
            _driveTypeRepository = driveTypeRepository;
            _bodyTypeRepository = bodyTypeRepository;
            _salesDataRepository = salesDataRepository;
            _usersRepository = usersRepository;
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;

        }

        public IActionResult Index()
        {
            return View(_vehicleRepository.GetVehicles());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            ViewBag.Models = _vehicleModelRepository.GetVehicleModel(id);
            return View(_vehicleRepository.GetVehicle(id));
        }

        [HttpGet]
        public IActionResult Sellcar()
        {
            ViewBag.Regions = _regionRepository.GetRegions();
            ViewBag.Models = _vehicleModelRepository.GetVehicleModels();
            ViewBag.Brands = _vehicleBrandRepository.GetVehicleBrands();
            ViewBag.FuelTypes = _fuelTypeRepository.GetFuelTypes();
            ViewBag.GearBoxes = _gearBoxRepository.GetGearBoxes();
            ViewBag.DriveTypes = _driveTypeRepository.GetDriveTypes();
            ViewBag.BodyTypes = _bodyTypeRepository.GetBodyTypes();
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Sellcar(VehicleCreateDto vehicleDto, IFormFile picture, string regionName, string bodyTypeName,
            string vehicleBrandName, string vehicleModelName, string gearBoxName, string driveTypeName, string fuelTypeName)
        {
            ViewBag.Regions = _regionRepository.GetRegions();
            ViewBag.Models = _vehicleModelRepository.GetVehicleModels();
            ViewBag.Brands = _vehicleBrandRepository.GetVehicleBrands();
            ViewBag.FuelTypes = _fuelTypeRepository.GetFuelTypes();
            ViewBag.GearBoxes = _gearBoxRepository.GetGearBoxes();
            ViewBag.DriveTypes = _driveTypeRepository.GetDriveTypes();
            ViewBag.BodyTypes = _bodyTypeRepository.GetBodyTypes();
            if (ModelState.IsValid)
            {
                string picturePath = Path.Combine(_webHostEnvironment.WebRootPath, "Images", picture.FileName);

                using (FileStream stream = new FileStream(picturePath, FileMode.Create))
                    picture.CopyTo(stream);
                string url = @"\Images\" + picture.FileName;

                vehicleDto.VehicleIconPath = url;

                var region = _regionRepository.GetRegionByName(regionName);
                if (region == null)
                {
                    region = new Region() { RegionName = regionName };
                    region = await _regionRepository.AddRegionAsync(region);
                }

                var bodyType = _bodyTypeRepository.GetBodyTypeByName(bodyTypeName);
                if (bodyType == null)
                {
                    bodyType = new BodyType() { BodyTypeName = bodyTypeName };
                    bodyType = await _bodyTypeRepository.AddBodyTypeAsync(bodyType);
                }

                var vehicleBrand = _vehicleBrandRepository.GetVehicleBrandByName(vehicleBrandName);
                if (vehicleBrand == null)
                {
                    vehicleBrand = new VehicleBrand() { VehicleBrandName = vehicleBrandName };
                    vehicleBrand = await _vehicleBrandRepository.AddVehicleBrandAsync(vehicleBrand);
                }

                var vehicleModel = _vehicleModelRepository.GetVehicleModelByName(vehicleModelName);
                if (vehicleModel == null)
                {
                    vehicleModel = new VehicleModel() { VehicleModelName = vehicleModelName, VehicleBrand = vehicleBrand };
                    vehicleModel = await _vehicleModelRepository.AddVehicleModelAsync(vehicleModel);
                }

                var gearBox = _gearBoxRepository.GetGearBoxByName(gearBoxName);
                if (gearBox == null)
                {
                    gearBox = new GearBox() { GearBoxName = gearBoxName };
                    gearBox = await _gearBoxRepository.AddGearBoxAsync(gearBox);
                }

                var driveType = _driveTypeRepository.GetDriveTypeByName(driveTypeName);
                if (driveType == null)
                {
                    driveType = new Core.DriveType() { DriveTypeName = driveTypeName };
                    driveType = await _driveTypeRepository.AddDriveTypeAsync(driveType);
                }

                var fuelType = _fuelTypeRepository.GetFuelTypeByName(fuelTypeName);
                if (fuelType == null)
                {
                    fuelType = new FuelType() { FuelTypeName = fuelTypeName };
                    fuelType = await _fuelTypeRepository.AddFuelTypeAsync(fuelType);
                }

                var saleData = new SalesData() { CreatedOn = DateTime.Now };

                var user = _usersRepository.GetUserByEmail(User.Identity.Name);
                if (user == null)
                {
                    user = new User() { Email = User.Identity.Name };
                }

                var vehicle = await _vehicleRepository.AddVehicleAsync(new Vehicle
                {
                    Region = region,
                    BodyType = bodyType,
                    VehicleModel = vehicleModel,
                    ProductionYear = vehicleDto.ProductionYear,
                    GearBox = gearBox,
                    DriveType = driveType,
                    StateNumber = String.IsNullOrEmpty(vehicleDto.StateNumber) ? "Не задано" : vehicleDto.StateNumber.ToUpper(),
                    NumberOfSeats = vehicleDto.NumberOfSeats,
                    NumberOfDoors = vehicleDto.NumberOfDoors,
                    Price_USD = vehicleDto.Price_USD,
                    Price_UAH = vehicleDto.Price_USD * 37,
                    Price_EUR = vehicleDto.Price_USD * 0.9984m,
                    isNew = vehicleDto.isNew,
                    Mileage = vehicleDto.Mileage,
                    VehicleIconPath = vehicleDto.VehicleIconPath,
                    FuelType = fuelType,
                    Color = vehicleDto.Color,
                    Description = vehicleDto.Description,
                    SalesData = saleData,
                    User = user
                });

                //vehicle.VehicleIconPath = Path.Combine("img", "upload", picturePath);
                return RedirectToAction("Index", "Home", new { id = vehicle.VehicleId });
            }
            return View(vehicleDto);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Regions = _regionRepository.GetRegions();
            ViewBag.Models = _vehicleModelRepository.GetVehicleModels();
            ViewBag.Brands = _vehicleBrandRepository.GetVehicleBrands();
            ViewBag.FuelTypes = _fuelTypeRepository.GetFuelTypes();
            ViewBag.GearBoxes = _gearBoxRepository.GetGearBoxes();
            ViewBag.DriveTypes = _driveTypeRepository.GetDriveTypes();
            ViewBag.BodyTypes = _bodyTypeRepository.GetBodyTypes();
            return View(await _vehicleRepository.GetVehicleDto(id));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(VehicleReadDto vehicleDto, string regionName, string bodyTypeName,
            string vehicleBrandName, string vehicleModelName, string gearBoxName, string driveTypeName, string fuelTypeName)
        {
            if (ModelState.IsValid)
            {

AutoOA/AutoOA.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoOA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoOA.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoOA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                        </li>
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Sellcar">Продати машину</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Користувачі</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;<a asp-area="" asp-controller="Home" asp-action="Index">2022 - AutoOA</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AutoOA/AutoOA.UI/Views/Shared/_NiceBlankLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Components / Accordion - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    @(await Html.PartialAsync("_NiceLayoutHead"))

</head>


<body>
    <main>
        @RenderBody()
    </main>

    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Template Main JS File -->
    <script src="/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>



</html>

AutoOA/AutoOA.UI/Views/Shared/_NiceLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Components / Accordion - NiceAdmin Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    @(await Html.PartialAsync("_NiceLayoutHead"))

</head>


<body>
    @if (User.IsInRole("Admin"))
    {
        @(await Html.PartialAsync("_NiceLayoutNavigation"))
    }
    @if (User.IsInRole("User")){

    }
    @(await Html.PartialAsync("_NiceLayoutHeader"))
    
    
   
    
    <main id="main" class="main">
    @RenderBody()
    </main>

    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Template Main JS File -->
    <script src="/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>



</html>

AutoOA/AutoOA.UI/Views/Shared/_NiceLayoutHead.cshtml
<!-- Favicons -->
<link href="/assets/img/favicon.png" rel="icon">
<link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.gstatic.com" rel="preconnect">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<link href="/assets/vendor/quill/quill.snow.css" rel="stylesheet">
<link href="/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
<link href="/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
<link href="/assets/vendor/simple-datatables/style.css" rel="stylesheet">

<!-- Template Main CSS File -->
<link href="/assets/css/style.css" rel="stylesheet">

<!-- =======================================================
* Template Name: NiceAdmin - v2.4.1
* Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
* Author: BootstrapMade.com
* License: https://bootstrapmade.com/license/
======================================================== -->

AutoOA/AutoOA.UI/Views/Shared/_NiceLayoutHeader.cshtml
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="/Home" class="logo d-flex align-items-center">
            <img src="/assets/img/car.png" alt="">
            <span class="d-none d-lg-block">AutoOA</span>
        </a>
        @if (User.IsInRole("Admin"))
        {
            <i class="bi bi-list toggle-sidebar-btn"></i>
        }
        @if (User.IsInRole("User"))
        {
            <div style="padding: 0 0px 0 15px">
                <a class="nav-profile" asp-controller="Vehicles" asp-action="Sellcar">
                    <span>Подати оголошення</span>
                </a>
            </div>
            <nav class="header-nav ms-auto">
                <div style="padding: 25px 0 0 0">
                    <ul>
                        <li>
                            <a class="nav-profile d-flex align-items-center  pe-0" href="#" data-bs-toggle="dropdown">
                                <h6>Валюта</h6>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end ">

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" href="/Home/IndexUAH">
                                        <i class="bi bi-currency-bitcoin"></i>
                                        <span>Гривня</span>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" href="/Home/Index">
                                        <i class="bi bi-currency-dollar"></i>
                                        <span>Долар</span>
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>

                                <li>
                                    <a class="dropdown-item d-flex align-items-center" href="/Home/IndexEUR">
                                        <i class="bi bi-currency-euro"></i>
                                        <span>Євро</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>

        }
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <div class="search-bar">
                <form method="get" asp-controller="Home" asp-action="Index" class="search-form d-flex align-items-center">
                    <input type="text" name="searchString" value="@ViewData["GetVehicleDetails"]" placeholder="Search" title="Enter search keyword">
                    <button type="submit" title="Search"><i class="bi bi-search"></i></button>
                </form>
            </div><!-- End Search Bar -->

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center  pe-0" href="#" data-bs-toggle="dropdown">
                    <h6><partial name="_LoginPartial" /></h6>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6><partial name="_LoginPartial" /></h6>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="/Identity/Account/Manage">
                            <i class="bi bi-person"></i>
                            <span>Мій профіль</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="/Identity/Account/Login">
                            <i class="bi bi-people"></i>
                            <span>Змінити користувача</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Вийти</button>
                                </form>
                            }
                        </a>
                    </li>
                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

AutoOA/AutoOA.UI/Views/Shared/_NiceLayoutNavigation.cshtml
  <!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        
        @if (User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a class="nav-link collapsed" href="/Users">
                <i class="bi bi-person"></i>
                <span>Список користувачів</span>
            </a>
        </li><!-- End F.A.Q Page Nav -->
        }
        @if (User.IsInRole("Moderator"))
        {
            <li class="nav-item">
                <a class="nav-link collapsed" href="/Vehicles/Index">
                <i class="bi bi-card-heading"></i>
                <span>Редагування оголошень</span>
            </a>
        </li><!-- End Contact Page Nav -->        
        }
    </ul>

</aside><!-- End Sidebar-->